rbac:
  create: true

namespaceToWatch: "default"

resourcesToWatch:
  daemonset: false
  deployment: false
  pod: true
  replicaset: false
  replicationcontroller: false
  services: false
  secret: false
  configmap: false
slack:
  channel: '#k8s-monitor'
  token: ''

image:
  registry: "registry.mooplab.com:8443"
  repository: "tools/kubewatch"
  tag: "v0.0.1"
  pullPolicy: "Always"
  